name: Validate Databricks Bundle (PR)

on:
  pull_request:
    paths:
      - "my_project/**"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    defaults:
      run:
        working-directory: ./my_project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Run unit tests
        run: uv run pytest -v

  validate:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate
        working-directory: ./my_project
        run: |
          databricks bundle validate -t dev \
            --var="service_principal_id=${{ secrets.DATABRICKS_CLIENT_ID }}"

      - name: Deploy (PR - Dev)
        working-directory: ./my_project
        run: |
          databricks bundle deploy -t dev \
            --var="service_principal_id=${{ secrets.DATABRICKS_CLIENT_ID }}"
            --var="service_principal_id=50e63598-ed43-4982-82f6-00565cbda8af"