name: Validate Databricks Bundle (PR)

on:
  pull_request:
    paths:
      - "my_project/**"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read

jobs:
  my_script_using_wif:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: https://dbc-e3f191cd-7308.cloud.databricks.com
      DATABRICKS_CLIENT_ID: 50e63598-ed43-4982-82f6-00565cbda8af

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run Databricks CLI commands
        run: databricks current-user me